sudo: false
dist: trusty
language: node_js
node_js:
  - "6"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - npm install

script:
  - npm run travis

after_success:
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
