"use strict";

const MATCH_MODE = exports.MATCH_MODE = {};
MATCH_MODE.WARN = 'warn';
MATCH_MODE.STRICT = 'strict';

const TEST_STAT = exports.TEST_STAT = {};
TEST_STAT.RELEASE = 1;
TEST_STAT.UNRELEASE_MATCHED = 0;
TEST_STAT.UNRELEASE_UNMATCHED = -1;

const DIFF_TYPE = exports.DIFF_TYPE = {};
DIFF_TYPE.CREATE = 1;
DIFF_TYPE.UPDATE = 0;
DIFF_TYPE.DELETE = -1;
