"use strict";

const MATCH_MODE = exports.MATCH_MODE = {};
MATCH_MODE.NORMAL = 'normal';
MATCH_MODE.WARN = 'warn';
MATCH_MODE.STRICT = 'strict';

const MATCH_STAT = exports.MATCH_STAT = {};
MATCH_STAT.RELEASE = 1;
MATCH_STAT.MATCHED = 0;
MATCH_STAT.UNMATCH = -1;

const DIFF_TYPE = exports.DIFF_TYPE = {};
DIFF_TYPE.CREATE = 1;
DIFF_TYPE.UPDATE = 0;
DIFF_TYPE.DELETE = -1;

const BUNDLE_TYPE = exports.BUNDLE_TYPE = {};
BUNDLE_TYPE.NEWEST = 'newest';
BUNDLE_TYPE.STABLE = 'stable';
BUNDLE_TYPE.BUNDLE = 'bundle';
